spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    servlet:
      path: /api
  mail:
    host: localhost
    port: 9025
